### ISSUE TITLE
seedValue error in "shop_store.dart"

### ISSUE THREAD

**Issue by mirazimzadeh** [lzyy/bloc_redux#1]
Hi @lzyy and thank you for this repository,

I got the error in **basket** and **item** variables with `seedValue: []`  

_The named parameter 'seedValue' isn't defined.
Try correcting the name to an existing named parameter, or defining a new parameter with this name.dart(undefined_named_parameter)_

`BehaviorSubject<List<ShoppingItem>>(seedValue: []);`
should Import any specific file in the header of file?

**Comment by limboy** [comment]
run `flutter packages get` in root dir which contains `pubspec.yaml` should fix this error.

if you are using VSCode, open `pubspec.yaml` then press the right top button should work.

<img width="199" alt="image" src="https://user-images.githubusercontent.com/35974/58444723-186f4400-812c-11e9-96d8-15e2dada6717.png">
